# Generated by Django 4.2.6 on 2023-10-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_healthrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='insulin',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='output',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
