# Generated by Django 4.2.6 on 2023-10-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_healthrecord_insulin_healthrecord_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='bp',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='func',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
